const types = {
  FETCH_ORGANIZATIONS_REQUEST: 'FETCH_ORGANIZATIONS_REQUEST',
  FETCH_ORGANIZATIONS_SUCCESS: 'FETCH_ORGANIZATIONS_SUCCESS',
  FETCH_ORGANIZATIONS_FAILURE: 'FETCH_ORGANIZATIONS_FAILURE',
  ADD_ORGANIZATION_REQUEST: 'ADD_ORGANIZATION_REQUEST',
  ADD_ORGANIZATION_SUCCESS: 'ADD_ORGANIZATION_SUCCESS',
  ADD_ORGANIZATION_FAILURE: 'ADD_ORGANIZATION_FAILURE',
  EDIT_ORGANIZATION_REQUEST: 'EDIT_ORGANIZATION_REQUEST',
  EDIT_ORGANIZATION_SUCCESS: 'EDIT_ORGANIZATION_SUCCESS',
  EDIT_ORGANIZATION_FAILURE: 'EDIT_ORGANIZATION_FAILURE',
};

export default types;
