const types = {
  LOGIN_REQUEST_TYPE: 'LOGIN_REQUEST_TYPE',
  LOGIN_SUCCESS_TYPE: 'LOGIN_SUCCESS_TYPE',
  LOGIN_FAILURE_TYPE: 'LOGIN_FAILURE_TYPE',
  INFO_REQUEST_TYPE: 'INFO_REQUEST_TYPE',
  INFO_SUCCESS_TYPE: 'INFO_SUCCESS_TYPE',
  INFO_FAILURE_TYPE: 'INFO_FAILURE_TYPE',
  LOGOUT_REQUEST_TYPE: 'LOGOUT_REQUEST_TYPE',
  LOGOUT_SUCCESS_TYPE: 'LOGOUT_SUCCESS_TYPE',
  LOGOUT_FAILURE_TYPE: 'LOGOUT_FAILURE_TYPE',
};

export default types;
