const types = {
  FETCH_SGA_PEOPLE_REQUEST: 'FETCH_SGA_PEOPLE_REQUEST',
  FETCH_SGA_PEOPLE_SUCCESS: 'FETCH_SGA_PEOPLE_SUCCESS',
  FETCH_SGA_PEOPLE_FAILURE: 'FETCH_SGA_PEOPLE_FAILURE',
  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
};

export default types;
