const types = {
  FETCH_AGENDA_BILLS_REQUEST: 'FETCH_AGENDA_BILLS_REQUEST',
  FETCH_AGENDA_BILLS_FAILURE: 'FETCH_AGENDA_BILLS_FAILURE',
  FETCH_AGENDA_BILLS_SUCCESS: 'FETCH_AGENDA_BILLS_SUCCESS',
  FETCH_SGA_PEOPLE_REQUEST: 'FETCH_SGA_PEOPLE_REQUEST',
  FETCH_SGA_PEOPLE_FAILURE: 'FETCH_SGA_PEOPLE_FAILURE',
  FETCH_SGA_PEOPLE_SUCCESS: 'FETCH_SGA_PEOPLE_SUCCESS',
  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  MARK_PRESENT_REQUEST: 'MARK_PRESENT_REQUEST',
  MARK_PRESENT_FAILURE: 'MARK_PRESENT_FAILURE',
  MARK_PRESENT_SUCCESS: 'MARK_PRESENT_SUCCESS',
};

export default types;
