const types = {
  FETCH_BILLS_REQUEST: 'FETCH_BILLS_REQUEST',
  FETCH_BILLS_FAILURE: 'FETCH_BILLS_FAILURE',
  FETCH_BILLS_SUCCESS: 'FETCH_BILLS_SUCCESS',
  CREATE_BILLS_REQUEST: 'CREATE_BILLS_REQUEST',
  CREATE_BILLS_FAILURE: 'CREATE_BILLS_FAILURE',
  CREATE_BILLS_SUCCESS: 'CREATE_BILLS_SUCCESS',
};

export default types;
