const types = {
  FETCH_BUDGETS_REQUEST: 'FETCH_BUDGETS_REQUEST',
  FETCH_BUDGETS_SUCCESS: 'FETCH_BUDGETS_SUCCESS',
  FETCH_BUDGETS_FAILURE: 'FETCH_BUDGETS_FAILURE',
  FETCH_LINE_ITEMS_REQUEST: 'FETCH_LINE_ITEMS_REQUEST',
  FETCH_LINE_ITEMS_SUCCESS: 'FETCH_LINE_ITEMS_SUCCESS',
  FETCH_LINE_ITEMS_FAILURE: 'FETCH_LINE_ITEMS_FAILURE',
};

export default types;
